project_id = "atblyrrczwcmnyhcdkto"

[functions.parse-rams-document]
verify_jwt = false

[functions.translate-rams]
verify_jwt = false

[functions.translate-toolbox-talk]
verify_jwt = false

[functions.translate-handbook]
verify_jwt = false

[functions.create-user]
verify_jwt = false
